//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "language")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::category_translation::Entity")]
    CategoryTranslation,
    #[sea_orm(has_many = "super::product_translation::Entity")]
    ProductTranslation,
    #[sea_orm(has_many = "super::sku_translation::Entity")]
    SkuTranslation,
}

impl Related<super::category_translation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryTranslation.def()
    }
}

impl Related<super::product_translation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductTranslation.def()
    }
}

impl Related<super::sku_translation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SkuTranslation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
